version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=server=movielibraryserver.mysql.database.azure.com;port=3306;database=MovieDB;user=adminuser;password=Jurnalist1!
